server:
  port: 33556
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 106.12.108.72:8848
  application:
    name: mo-yu-jun
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.12.108.72:3306/firelight_user_content?characterEncoding=utf-8&useSSL=false&useUnicode=true
    username: root
    password: mengmengmeng0501
  redis:
    database: 1 # 使用1号库
    host: 106.12.108.72
    port: 6379
    password: mengmengmeng0501
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: Asia/Shanghai
mybatis-plus:
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 输出Sql语句执行日志
  global-config:
    db-config:
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:cn/dreamjun/my/mapper/xml/*xml


qiniu:
  accesskey: K87mV6a-eQki1ggKOju3-Q7WlbbdF5chDMvt_hPf
  secretkey: PgClFzbuTffxQ31SgxkCDvfutfdXDzPDvpro-55I
  bucket: dreamjunorder
  path: qiniuyun.dreamjun.cn/
  max-file-size: 4
  admin:
    category: admin/
